# Generated by Django 3.0.5 on 2022-04-26 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_auto_20210325_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='entrytime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 23, 29, 53, 158486)),
        ),
    ]
