# Generated by Django 3.0.5 on 2022-04-26 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0007_auto_20220426_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='entrytime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 23, 39, 31, 437433)),
        ),
    ]
