# Generated by Django 3.0.5 on 2022-04-26 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0008_auto_20220426_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='entrytime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 23, 45, 35, 161289)),
        ),
    ]
