# Generated by Django 4.0.4 on 2022-04-28 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0012_alter_farmers_entrytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='entrytime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 9, 53, 52, 320150)),
        ),
    ]
